"""add coat to horses

Revision ID: 510b9708a0d2
Revises: c5570ea7e7ec
Create Date: 2026-06-07 13:35:45.014115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '510b9708a0d2'
down_revision: Union[str, Sequence[str], None] = 'c5570ea7e7ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('horses', sa.Column('coat', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('horses', 'coat')
    # ### end Alembic commands ###
