"""add nullable to Horse in title, img, age, record, trainer

Revision ID: aaa627f1b5e8
Revises: 510b9708a0d2
Create Date: 2026-06-07 13:38:06.629856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aaa627f1b5e8'
down_revision: Union[str, Sequence[str], None] = '510b9708a0d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
