"""initial

Revision ID: c5570ea7e7ec
Revises: 
Create Date: 2026-06-07 13:34:12.241029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5570ea7e7ec'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('farms_owner_id_fkey'), 'farms', type_='foreignkey')
    op.create_foreign_key(None, 'farms', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    op.add_column('horses', sa.Column('farm_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'horses', 'farms', ['farm_id'], ['id'])
    op.add_column('users', sa.Column('name', sa.String(), nullable=False))
    op.add_column('users', sa.Column('role', sa.String(), nullable=True))
    op.add_column('users', sa.Column('phone_code', sa.String(), nullable=True))
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_number')
    op.drop_column('users', 'phone_code')
    op.drop_column('users', 'role')
    op.drop_column('users', 'name')
    op.drop_constraint(None, 'horses', type_='foreignkey')
    op.drop_column('horses', 'farm_id')
    op.drop_constraint(None, 'farms', type_='foreignkey')
    op.create_foreign_key(op.f('farms_owner_id_fkey'), 'farms', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###
